name = "pseo-app"
client_id = "5dd568528bc4eee18c0cdfe5325fab39"
application_url = "https://geopages.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dupe-test-store.myshopify.com"

[access_scopes]
scopes = "write_content,read_content,write_metaobjects,read_metaobjects,read_themes,write_themes,read_online_store_navigation,write_online_store_navigation"

[auth]
redirect_urls = [
  "https://geopages.fly.dev/auth/callback",
  "https://geopages.fly.dev/auth/shopify/callback",
  "https://geopages.fly.dev/exitiframe"
]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://geopages.fly.dev/apps/service-areas"
subpath = "service-areas"
prefix = "apps"

[pos]
embedded = false
