import type { MetaFunction } from "@remix-run/node";

export const meta: MetaFunction = () => [
  { title: "Terms of Service — Geopages" },
  { name: "robots", content: "index, follow" },
];

const LAST_UPDATED = "June 22, 2026";

export default function Terms() {
  return (
    <main style={styles.page}>
      <article style={styles.article}>
        <header style={styles.header}>
          <h1 style={styles.h1}>Terms of Service</h1>
          <p style={styles.lastUpdated}>Last updated: {LAST_UPDATED}</p>
        </header>

        <section>
          <h2 style={styles.h2}>1. Acceptance</h2>
          <p>
            By installing or using Geopages (&quot;the app&quot;) on a Shopify store, you
            (&quot;the merchant&quot;) agree to these Terms of Service. If you do not
            agree, do not install or use the app.
          </p>
        </section>

        <section>
          <h2 style={styles.h2}>2. The service</h2>
          <p>
            Geopages generates AI-written SEO landing pages for combinations of services
            and locations the merchant configures. Pages are stored in the app database
            and served on the merchant&apos;s storefront via Shopify App Proxy at
            <code> /apps/service-areas/&lt;slug&gt;</code>.
          </p>
        </section>

        <section>
          <h2 style={styles.h2}>3. Subscription and billing</h2>
          <ul>
            <li>The app is offered for $30 USD per month, billed monthly through Shopify&apos;s Billing API</li>
            <li>New installs receive a 3-day free trial; the first charge occurs on day 4</li>
            <li>Development stores are billed in test mode (no real charge)</li>
            <li>Cancellation takes effect at the end of the current billing period</li>
            <li>No refunds are issued for partial periods</li>
            <li>Page generation is disabled while the subscription is not active</li>
          </ul>
        </section>

        <section>
          <h2 style={styles.h2}>4. Merchant responsibilities</h2>
          <p>The merchant is responsible for:</p>
          <ul>
            <li>The accuracy of the services, locations, and business information they enter</li>
            <li>Providing their own API keys for OpenAI, Google Gemini, Google Maps, and Unsplash, and paying any usage fees those services charge</li>
            <li>Reviewing AI-generated content before publishing to ensure it is accurate, lawful, and appropriate for their business</li>
            <li>Complying with the Shopify Acceptable Use Policy, Google&apos;s Webmaster Guidelines, and any applicable law in jurisdictions where the storefront operates</li>
          </ul>
        </section>

        <section>
          <h2 style={styles.h2}>5. AI-generated content disclaimer</h2>
          <p>
            Pages are generated by large language models which can produce inaccurate,
            outdated, or fabricated information. The merchant is solely responsible for
            verifying content before it is published to the public storefront. Geopages
            makes no warranty that generated content will rank in search results,
            generate traffic, or convert to sales.
          </p>
        </section>

        <section>
          <h2 style={styles.h2}>6. SEO disclaimer</h2>
          <p>
            Search-engine rankings depend on many factors outside the app&apos;s control,
            including content quality, site authority, backlinks, competitor activity,
            and search-engine algorithm updates. Programmatic content generation at
            scale carries known risks of being treated as low-quality or doorway
            content by search engines. Geopages does not guarantee indexation,
            ranking position, traffic, or revenue from generated pages.
          </p>
        </section>

        <section>
          <h2 style={styles.h2}>7. Acceptable use</h2>
          <p>The merchant agrees not to use the app to:</p>
          <ul>
            <li>Generate content that is illegal, defamatory, deceptive, or that infringes intellectual property</li>
            <li>Misrepresent the merchant&apos;s business, service areas, qualifications, or affiliations</li>
            <li>Violate search-engine guidelines in a manner likely to result in penalties</li>
            <li>Generate content for industries prohibited by Shopify&apos;s Acceptable Use Policy</li>
            <li>Attempt to reverse-engineer, abuse, or interfere with the app or its infrastructure</li>
          </ul>
        </section>

        <section>
          <h2 style={styles.h2}>8. Service availability</h2>
          <p>
            The app is provided on an &quot;as is&quot; and &quot;as available&quot; basis.
            We aim for high availability but do not guarantee uninterrupted service.
            Generated pages served via App Proxy require the app&apos;s servers to be
            online; if the app experiences an outage, pages will return errors during
            the outage.
          </p>
        </section>

        <section>
          <h2 style={styles.h2}>9. Limitation of liability</h2>
          <p>
            To the maximum extent permitted by law, Geopages and its operators are not
            liable for any indirect, incidental, special, consequential, or punitive
            damages, including loss of revenue, traffic, rankings, profits, data, or
            goodwill, arising from use of or inability to use the app. Aggregate
            liability is limited to the amount the merchant has paid to Geopages in
            the 12 months preceding the claim.
          </p>
        </section>

        <section>
          <h2 style={styles.h2}>10. Termination</h2>
          <p>
            The merchant may uninstall the app at any time from the Shopify admin.
            Geopages may suspend or terminate accounts that violate these terms or
            Shopify&apos;s policies. Upon uninstall, data is retained for ~48 hours and
            then permanently deleted in response to Shopify&apos;s <code>shop/redact</code>
            webhook.
          </p>
        </section>

        <section>
          <h2 style={styles.h2}>11. Changes to these terms</h2>
          <p>
            We may update these terms as the app evolves. The &quot;Last updated&quot;
            date above reflects the current version. Continued use of the app after
            changes constitutes acceptance.
          </p>
        </section>

        <section>
          <h2 style={styles.h2}>12. Contact</h2>
          <p>
            Questions about these terms? Reach the support address listed in the app&apos;s
            Shopify App Store listing.
          </p>
        </section>

        <footer style={styles.footer}>
          <p>
            <a href="/legal/privacy" style={styles.link}>Privacy Policy</a>
          </p>
        </footer>
      </article>
    </main>
  );
}

const styles = {
  page: {
    minHeight: "100vh",
    background: "#fafafa",
    padding: "40px 16px 80px",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    color: "#1a1a1a",
    lineHeight: 1.7,
  },
  article: {
    maxWidth: 760,
    margin: "0 auto",
    background: "white",
    padding: "48px 40px",
    borderRadius: 12,
    boxShadow: "0 1px 4px rgba(0,0,0,0.05)",
  },
  header: {
    marginBottom: 32,
    paddingBottom: 16,
    borderBottom: "1px solid #e5e5e5",
  },
  h1: {
    fontSize: 36,
    fontWeight: 700,
    letterSpacing: "-0.02em",
    margin: 0,
  },
  h2: {
    fontSize: 22,
    fontWeight: 700,
    letterSpacing: "-0.01em",
    margin: "32px 0 12px",
  },
  lastUpdated: {
    color: "#6d7175",
    fontSize: 14,
    marginTop: 8,
    marginBottom: 0,
  },
  footer: {
    marginTop: 48,
    paddingTop: 24,
    borderTop: "1px solid #e5e5e5",
    fontSize: 14,
    color: "#6d7175",
  },
  link: {
    color: "#006fbb",
    textDecoration: "underline",
  },
} as const;
